run:
  timeout: 5m

linters-settings:
  wrapcheck:
    ignoreSigs:
      - fmt.Errorf
  gomnd:
    settings:
      mnd:
        ignored-functions: os.*

linters:
  enable-all: true
  disable:
  # deprecated:
    - ifshort
    - varcheck
    - deadcode
    - golint
    - structcheck
    - interfacer
    - nosnakecase
    - maligned
    - scopelint
    - exhaustivestruct

  # generics:
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

    - gci
    - varnamelen
    - predeclared
    - paralleltest
    - depguard
    - exhaustruct
    - gofmt
    - gofumpt
    - goimports
    - nolintlint
    - tagliatelle
