title: "Article title here"
img_folder: "path/to/img/folder"
title_img_path: 
  - "path/to/title.png"
caption_img_path: 
  - "path/to/caption.png"
auth_token: "abcdefghijklmnopqrstuvwxyz123"
output: "chapter_link.txt"
auto_open: true

author_name: "Author Name Full"
author_short_name: "Short Author Name"
author_url: "https://t.me/ZUMORl"
